name: Keep Codespace Alive

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: self-hosted

    steps:
      - name: Keep Codespace Alive
        run: echo "Keeping Codespace alive for 6 minutes"


