name: Keep Minecraft Server Alive

on:
  schedule:
    - cron: '0 */12 * * *' # Run every 12 hours

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Keep Codespace Alive
        run: echo "Keeping Codespace alive for 12 hours"
