name: Start Minecraft Server

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours

jobs:
  start-server:
    runs-on: ubuntu-latest

    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Start Ngrok and Minecraft Server
        run: |
          nohup ./ngrok authtoken 2fv2pv3qM5CXUtyjwCJeD2cwkVR_5v1JgoaQAUcqNrkPuwoPt &
          sleep 1
          nohup ./ngrok tcp 25565 &
          sleep 10
          java -Xmx7G -jar server.jar nogui

