name: Start Minecraft Server

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours

jobs:
  start-server:
    runs-on: ubuntu-latest

    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Screen
        run: sudo apt-get install screen -y

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Create Plugins Directory
        run: mkdir -p plugins

      - name: Download Plugins
        run: |
          wget -O plugins/DiscordSRV.jar <URL_TO_DISCORDSRV_JAR>
          wget -O plugins/ClearLagg.jar <URL_TO_CLEARLAGG_JAR>
          wget -O plugins/SimpleTPA.jar <URL_TO_SIMPLETPA_JAR>

      - name: Modify EULA
        run: |
          sed -i 's/eula=false/eula=true/' eula.txt

      - name: Modify server.properties
        run: |
          sed -i 's/online-mode=true/online-mode=false/' server.properties

      - name: Start Ngrok and Minecraft Server
        run: |
          screen -dmS ngrok ./ngrok authtoken $NGROK_AUTH_TOKEN
          sleep 1
          screen -S ngrok -X stuff './ngrok tcp 25565\n'
          sleep 10
          java -Xmx7G -jar server.jar nogui
